version: '3.8'

services:
  docuspotlight:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-30267}:5050"  # 后端API端口
      - "${FRONTEND_PORT:-32211}:8080"  # 前端服务端口
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/results:/app/backend/results
      - ./backend/extract_results:/app/backend/extract_results
      - ./backend/parse_results:/app/backend/parse_results
    environment:
      - FLASK_ENV=production
    restart: unless-stopped